#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 18 09:54:43 2018

@author: vishal
"""
class Node:
    def __init__(self):
        self.left = None
        self.right = None
        self.data = None
        
obj = Node()