#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May 13 23:14:29 2018

@author: vishal
"""

arr = [1,2,3,4,5]
print(len(arr))

print(arr[4])

def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i-1
        
        while (j >=0 and key < arr[j]):
            arr[j+1] = arr[j]
            j-=1
        arr[j+1] = key
    return arr
        
def partition(arr,low,high):
    i = ( low-1 )        
    pivot = arr[high]
 
    for j in range(low , high):
 
        if   arr[j] <= pivot:
         
            i = i+1
            arr[i],arr[j] = arr[j],arr[i]
 
    arr[i+1],arr[high] = arr[high],arr[i+1]
    return ( i+1 )
            
        
def quick_sort(arr,low, high):
    if low< high:
        pi = partition(arr, low, high)
        quick_sort(arr,low, pi-1)
        quick_sort(arr, pi+1, high)
        

choice = 1
arr = []

while (choice >0 and choice <=3):
    print("1 Insert \n2 for Sorting \n3 Print")
    choice = int(input())
    if choice == 1:
        arr.append(int(input()))
    elif choice == 2:
        arr = insertion_sort(arr)
        print("After Sorting", arr)
    elif choice ==3:
        print("arr :",arr)
