#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 16 13:06:32 2018

@author: vishal
"""

n = 5
x = [10,40,30,50,20]
mean = 0 
for val in x:
    mean = mean +val

mean /=n

variance= 0
for i in range(len(x)):
    variance += (x[i] - mean) ** 2
    
variance /=n

import math
std = math.sqrt(variance)

print(round(std, 1))